services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./src:/app/src  # For hot-reloading during development
      - ./pyproject.toml:/app/pyproject.toml  # Make project metadata available
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    env_file:
      - .env
    # Override the default command to enable hot-reloading
    command: sh -c "exec uvicorn openai_api_blueprint.main:app --host ${HOST:-0.0.0.0} --port ${PORT:-8000} --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    # Enable watch mode for live rebuilds
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
